name: Markdown Processing
on:
  pull_request:  # pull_requestイベントに対してトリガーされるように設定
  push:
    branches:
      - main  # mainブランチへのpushでトリガー

jobs:
  update-docs-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown autodocs

      - name: Lint Markdown
        uses: articulate/actions-markdownlint@v1
        with:
          files: './README.md'
          ignore: node_modules
      
