name: Markdown Processing
on:
  pull_request:  # pull_requestイベントに対してトリガーされるように設定
  push:
    branches:
      - main  # mainブランチへのpushでトリガー

jobs:
  update-docs-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Markdown autodocs
        uses: dineshsonachalam/markdown-autodocs@v1.0.7
        with:
          commit_author: "GitHub Actions <actions@github.com>"
          commit_user_email: "actions@github.com"
          commit_message: "Apply automatic changes"
          branch: "main"  # ここは自動化したいブランチに合わせてください
          output_file_paths: "./README.md"
          categories: "[code-block,json-to-html-table,workflow-artifact-table]"

      - name: Lint Markdown
        uses: articulate/actions-markdownlint@v1
        with:
          files: './README.md'
          ignore: node_modules

